### ISSUE TITLE
Receiver gets "you don't have Omemo message" even though they do

### ISSUE THREAD

**Issue by n8fr8** [vanitasvitae/Smack#13]
Testing against ChatSecure iOS, it receives and decrypts my omemo message successfully, but it also receives and shows the "I sent you an OMEMO encrypt message but you client doesn't seem to support that...".

**Comment by vanitasvitae** [comment]
That's actually a bug in ChatSecure-iOS (see https://github.com/ChatSecure/ChatSecure-iOS/issues/717). The OMEMO specification states that the client should treat the decrypted payload element as the body of the message. ChatSecure should recognize the EME tag (XEP-0380) and hide the body in encrypted messages.

You should see the same result when decrypting messages with ChatSecure-iOS that were sent from Gajim or Conversations.

As a workaround, you could remove [this line](https://github.com/vanitasvitae/smack-omemo/blob/4.2/smack-omemo/src/main/java/org/jivesoftware/smackx/omemo/OmemoManager.java#L214) from the code.

**Comment by n8fr8** [comment]
Hey @chrisballinger what do you think?

**Comment by chrisballinger** [comment]
@n8fr8 I have no objections to changing this and adding 0380 hints for OMEMO and OTR. I wasn't aware that plaintext messages were being displayed in addition to the OMEMO payloads. I've never seen plaintext messages when receiving OMEMO messages from Conversations and haven't tested much with Gajim.

Sending out the additional fallback message is a good idea and we should try to standardize on something that includes a generic link for additional information about OMEMO / compatible clients.

**Comment by vanitasvitae** [comment]
@n8fr8 I made appending the OMEMO hint optional, as well as some other things. You might want to give the [configuration options](https://github.com/vanitasvitae/smack-omemo/blob/4.2/smack-omemo/src/main/java/org/jivesoftware/smackx/omemo/util/OmemoConstants.java#L25) a try ;)
